### ISSUE TITLE
[BE] .gitignore 수정 및 .idea 폴더 삭제

### ISSUE THREAD

**Issue by cipp00h** [Rainbow-SSAP/SSAP-GaNeung#3]
## 작업 사항

> backend 폴더 상위에 있는 .gitignore 수정 및 .idea 폴더 삭제

## To-do
- [x] .gitignore 파일에 .DS_Store, .idea 내용 추가
- [x] .idea 폴더 삭제

## 기타사항

> 기타 사항을 작성해주세요

**Comment by SSUK-H** [comment]
혹시 최상단에 백엔드는 .gitignore 파일이 필요한가요?

**Comment by cipp00h** [comment]
> 혹시 최상단에 백엔드는 .gitignore 파일이 필요한가요?

네~ 필요합니다
